#!/bin/bash

if [ "$1" == "" ]; then
    echo "Usage: $0 <directory-to-enroll>"
    exit 1
else
    echo "Checking if $1 is a directory...."
    if [ -d "$1" ]; then
        echo "Enrolling directory $1"
        echo "$1" >> /etc/pesticide/pesticide.conf
    else
        echo "$1 is not a directory"
        exit 1
    fi
fi